#!/bin/bash

echo "🚀 NoteUno Deployment Guide"
echo "=========================="
echo ""
echo "Required Environment Variables for Vercel:"
echo ""
echo "1. MONGO_URI"
echo "   - Your MongoDB Atlas connection string"
echo "   - Example: mongodb+srv://username:password@cluster.mongodb.net/database"
echo ""
echo "2. JWT_SECRET"
echo "   - A secure random string for JWT tokens"
echo "   - Example: your-super-secret-jwt-key-here"
echo ""
echo "3. FRONTEND_URL"
echo "   - Your Vercel app URL"
echo "   - Value: https://noteuno.vercel.app"
echo ""
echo "4. NODE_ENV"
echo "   - Environment setting"
echo "   - Value: production"
echo ""
echo "Steps to add these in Vercel:"
echo "1. Go to https://vercel.com/dashboard"
echo "2. Select your NoteUno project"
echo "3. Click 'Settings' tab"
echo "4. Click 'Environment Variables'"
echo "5. Add each variable above"
echo "6. Redeploy your application"
echo ""
echo "After adding environment variables, your API endpoints should work!"
echo "Test with: https://your-app-name.vercel.app/api/health"
